version: '3.8'

services:
  nginx-reverse:
    image: nginx
    ports:
      - 80:80
      - 443:443
      - 3306:3306
    volumes:
      - nginx.conf:/etc/nginx/nginx.conf
      - ../ssl:/etc/nginx/ssl
    env_file:
      - .env_reverse_nginx
    networks:
      - private_develop

networks:
  private_develop: